### PR TITLE
Reword common description text

### PR DESCRIPTION
**Pull request by vecerap**
I reworded the welcome text on the website which was the first thing what hit me in the eyes. Reworded version sounds better in my opinion.

### CODE REVIEW

**Review by joshika39 — CHANGES_REQUESTED** [review]
If you want to change the English (source) language, do it so in the `/src` folder

**Comment by vecerap** [comment]
> If you want to change the English (source) language, do it so in the `/src` folder

@joshika39 Changing only the src/en file would leave for yet untranslated files different "original" version than what the current English is. What I understood from codebase is that yet untranslated files originate from default English file, so if default English file is changed, so the source English files in all untranslated languages (which right now are all in fact) must change.

I would like to clarify how does the default placeholder values for untranslated languages work. Thank you.

**Comment by joshika39** [comment]
Thank you for you contribution!

The Crowdin project was still in setup. 

Now, you will have to rebase to the main, and only do your changes in the `/i18n/en/en,json` the other changes will get ignored.
The untranslated languages are not yet enabled, hence, there's no meaning changing them from code. You will have to do it through Crowdin.

Changes: the `/src` folder has been deleted to align the source with the target languages.

**Comment by joshika39** [comment]
Now the crowdin project is ready for accept contributors. 

But as for you, who wants to modify the source language, you have to edit the `/i18n/en/dictionary.json`

Let me know if you have further questions

**Comment by vecerap** [comment]
Ok based on the latest comment I left the change only in dictionary file.

**Review by joshika39 — APPROVED** [review]
Cool, it seems alright. Merging it. 

Thanks for your help!

**Pull request merged**
