### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by joshika39**

### CODE REVIEW

**Comment by KurococLiu** [comment]
I suggest distinguishing between Simplified Chinese and Traditional Chinese by zh-hans and zh-hant or by zh-cn and zh-tw

**Comment by joshika39** [comment]
> I suggest distinguishing between Simplified Chinese and Traditional Chinese by zh-hans and zh-hant or by zh-cn and zh-tw

@KurococLiu, Thank you, I'll get back to you when I did it.

**Comment by KurococLiu** [comment]
> > I suggest distinguishing between Simplified Chinese and Traditional Chinese by zh-hans and zh-hant or by zh-cn and zh-tw
> 
> @KurococLiu, Thank you, I'll get back to you when I did it.

You're welcome. It's a great project, and I'm happy to participate and contribute.

**Comment by joshika39** [comment]
Can you send me what would you like to see here (the language selection): 
image

**Comment by KurococLiu** [comment]
> Can you send me what would you like to see here (the language selection): image

Simplified Chinese：简体中文
Traditional Chinese：正體中文

**Comment by joshika39** [comment]
Thank you once again @KurococLiu !

The languages are in and they are on the path to production!

**Pull request merged**
