### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by joshika39**

### CODE REVIEW

**Comment by KurococLiu** [comment]
How to translate documents that I can translate into Simplified Chinese

**Comment by joshika39** [comment]
What do you mean under documents? 
Documentation?

**Comment by KurococLiu** [comment]
> What do you mean under documents?你说的“文档”下是什么意思？What do you mean under documents? Documentation? 文档？ Documentation?

https://docs.floorp.app/

**Comment by joshika39** [comment]
Ah yes, the documentation! You need to give us a little time, as the languages are being refactored to support open contribution!

Thank you!

**Pull request merged**
